#cloud-config
hostname: opensuse-demo

users:
  - name: aladroc
    gecos: Aladroc User
    shell: /bin/bash
    groups: users, sudo
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    lock_passwd: false
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCfsb4ArX5NyywwwZXojzwwcj3sMtCkb7PWkChK4TuLwP+mh4U1g3xcjK/2NavJQ0VIdyLrjkXk2JJZjoVlW4KYc9ycGMEaeNRXpfTg9SPtHJpTM/EHXV/pGsPGBVRXecHNsu6cFjvab4JwlyrxOMaf5YOzpHIclSEpgBLhTAKtEoVMkITCrpgZNPgOE8MKjBd74371ma+Z4MwSZI7pSp5iqkyNtEgXYV+aAV1zsuF52gWj0p702Ogz0UNrkTwQpWQHhc80tiu/Z4kpY2KvtpGzKfZb1EsPhcG6ws1/Rdx1KazxSEusJqMf49ma8DQsh9sMDVteSzUNS+awQ2Y2vljQEDrckea3SqVKD4GHtq8ZhmhosbLMBYSa25D2hwOFcsegxexlxV6eBMxVS5v0M/xncjUpU3QIQRCQy2mcgJrqK2fft2muCFUOjuw/bpyQIPX9tTDJaZZeByCzscurCtJx09qOSGrmuVZH3FEu9CSlQtZkUGcq9lJfQTO8pE9bgFOfkRAVULsoafHalorjMS+c7syda3w0Ia5iKT71FlvjVRtkWMK95dDQbjq1YDzUVmBM4H1lWjYW3LkUbC6n/0wrfyKg0+02pM7gh56GqnKGYSS5q/U/WwMK4YJaaPpb1pXthlMeSQyqfsr6QCUxcsTebx7bqpC1r4PHcbGroz3reQ== aladroc@josrom01-aladroc#StandardKey

ssh_pwauth: true
disable_root: false

chpasswd:
  list: |
    aladroc:opensuse
  expire: False

packages:
  - qemu-guest-agent
  - net-tools
  - btop
  - python312
  - python312-pip

package_update: false
package_upgrade: false

runcmd:
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent
